name: Testspace Cloud
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.stridespace.com
          token:  ${{ secrets.TESTSPACE_TOKEN }}
        env:
          TESTSPACE_CLIENT_VER: dev
      - run: npm install
      - run: npm test || true
      - name: Push test result to Testspace
        run: |
          testspace "results/cypress/e2e/test*.xml{cypress/e2e}" "results/cypress/e2e/**/test*.xml{cypress/e2e}"
        if: always()